### ISSUE TITLE
How to make shadow effect in circle view with cornerRadius

### ISSUE THREAD

**Issue by litt1e-p** [PierrePerrin/ShadowView#3]
@PierrePerrin Hi, does [ShadowView](https://github.com/PierrePerrin/ShadowView) support circle view with cornerRadius, I did tried it out. here is my code:

**Comment by PierrePerrin** [comment]
Hi I think tou forget to paste your code. 
Normally the Shadow view uses its subview to prepare the shadow.
If you set a rounded subview, you shadow should be sound. 
If tou are using a sinple UIView and want a circle shadowView you need to set the shadowPath to nil or override it.

**Comment by litt1e-p** [comment]
```
import UIKit
import SnapKit
import ShadowView

class gView: UIView {

    override init(frame: CGRect) {
        super.init(frame: frame)
        addSubview(bgView)
        bgView.addSubview(imgView)
        bgView.snp.makeConstraints { (m) in
            m.centerX.equalTo(self)
            m.centerY.equalTo(self.snp.bottom).multipliedBy(1/3.0)
            m.width.equalTo(self).multipliedBy(1/2.0)
            m.height.equalTo(bgView.snp.width)
        }
        imgView.snp.makeConstraints { (m) in
            m.edges.equalTo(bgView)
        }
        imgView.layer.cornerRadius = self.frame.size.width / 4.0
        imgView.layer.masksToBounds = true
        bgView.shadowRadius = 10
        bgView.shadowOffset = CGSize(width: 5, height: 5)
        bgView.shadowOpacity = 0.5
    }

   func assign(with img: UIImage) {
    	bgView.updateShadow()
   }

   fileprivate lazy var bgView: ShadowView = {
        let v = ShadowView(color: .clear)
        return v
    } ()
    
    fileprivate lazy var imgView: UIImageView = {
        let iv = UIImageView(contentMode: UIViewContentMode.scaleAspectFill, image: nil)
        return iv
    } ()
}
```

here is my code, and it crashed
![](http://ww3.sinaimg.cn/large/006tKfTcgy1fm1aiite78j31e40qwjwd.jpg)
I wondering that maybe `updateShadow` too early?

**Comment by PierrePerrin** [comment]
Yes if you assign your image before the context is created (when the view is going to be displayed) it won't work.
I should make the context optional in order to prevent the crash.

**Comment by PierrePerrin** [comment]
Sorry, you must set a frame to the shadow view before adding it to your view.
More than that, you never set the image of your imageView.

**Comment by litt1e-p** [comment]
I modify the func `assign()`:
```
func assign(with url: URL) {
    	imgView.yy_setImage(with: url, placeholder: nil, options: [], completion: { (image, url, type, stage, error) in
            if let _ = image {
                bgView.updateShadow()
            }
        })
  }
```
but it still not work.
![](http://ww3.sinaimg.cn/large/006tNc79gy1fm1fif51czj30me0kujst.jpg)

**Comment by PierrePerrin** [comment]
Is shadow view working in the example ?
Do try to edit the example to make the effect you want ? 
Without debugging I won't be able to help you with your problem...

**Comment by litt1e-p** [comment]
yes, I think the reason is the image of the imageView, it is nil when get `asImage` from CALayer. 
![](http://ww4.sinaimg.cn/large/006tKfTcgy1fm4isacwn0j31be144k0w.jpg)
and I wonder why get image from layer instead of getting image from imageView's subView. It works after I modify codes below:
![](http://ww4.sinaimg.cn/large/006tKfTcgy1fm4mslj7trj311i0h0q7t.jpg)

**Comment by litt1e-p** [comment]
@PierrePerrin sorry about previous bug I made, I fixed it now by set bgView's frame and image. Thanks again

**Comment by litt1e-p** [comment]
And by the way, the version `1.2.1` is not found in [cocoapods](https://cocoapods.org/?q=ShadowView)
