### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by leo1mml** [PierrePerrin/ShadowView#5]
I tried to use it with a collection view
I could'n find the:
`shadowView.highPerformanceBlur`
Could you give more detailed info about how to use it programmatically?
I would love to use this framework, it seems awesome!

**Comment by PierrePerrin** [comment]
Hi Leo, 

Sorry for the late response. Do you manage to use the framework. 
Actually the framework is still working, but it's not very adapted for CollectionViews. The blur generation is quiet long and the apparition could visible on scrolling (Specially on old device with less graphical capabilities)

**Comment by leo1mml** [comment]
Oh, I don’nt know why, but now it is working! You guys did a great job!

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leo1mml** [comment]
Now it is working, thanks for the great job!
