### ISSUE TITLE
addSubview so lag

### ISSUE THREAD

**Issue by fung199609** [PierrePerrin/ShadowView#8]
When I add the shadowContainerView be the subview.
It's so slow and feel lag.

ShadowView *shadowContainerView = [[ShadowView alloc] init];
shadowContainerView.frame = self.bounds;
shadowContainerView.autoresizingMask = (UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight);
  shadowContainerView.shadowOffset = CGSizeMake(0, self.shadowOffset);
  shadowContainerView.shadowRadius = self.radius;
  shadowContainerView.shadowScale = 0.9;
  
  CGRect frame = self.frame;
  frame.size.height = self.height+self.shadowOffset;
  self.frame = frame;
  
  [self addSubview: shadowContainerView];     //this line make the program so slow and lag
  [shadowContainerView addSubview:_frontImgView];
  _frontImgView.center = shadowContainerView.center;

**Comment by PierrePerrin** [comment]
Hi, sorry for the late response.  Do you actually found a way to make things smoother? 
At which moment do you add the subview in your View?
The shadow radius is a demanding parameter, did you try to low it down? 

Pierre

**Comment by fung199609** [comment]
no. it still lag about 1 second
